import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { analyzeFrame, getFrameDetails, resolveMediaUrl, updateFilmMetadata } from "../api/client";

const pct = (v) => `${Math.round(v * 100)}%`;
const Field = ({label, value, kind="Measured"}) => <div className="signal"><span>{label}<i>{kind}</i></span><strong>{value ?? "Unavailable"}</strong></div>;
export default function FrameDetailPage() {
  const { frameId } = useParams(); const [detail,setDetail]=useState(null); const [busy,setBusy]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState(false);
  const load=async()=>{setBusy(true);try{setDetail((await getFrameDetails(frameId)).data);setError("");}catch(e){setError(e.response?.data?.detail||"Backend unavailable. Start FrameVault and retry.");}finally{setBusy(false)}};
  useEffect(()=>{load()},[frameId]);
  const run=async()=>{setBusy(true);try{await analyzeFrame(frameId);await load()}catch(e){setError(e.response?.data?.detail||e.message);setBusy(false)}};
  const save=async(e)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.year=data.year?Number(data.year):null;await updateFilmMetadata(detail.film.id,data);setEditing(false);await load()};
  if(!detail) return <div className="empty-state">{busy?"Preparing the light table…":<>{error}<br/><button className="button-secondary mt-4" onClick={load}>Retry</button></>}</div>;
  const {frame,film,shot,media_asset}=detail; const analysis=detail.analyses.at(-1); const d=analysis?.results;
  return <section className="frame-detail"><div className="detail-toolbar"><Link className="button-ghost" to={`/films/${film.id}`}>← Collection</Link><span className="status-chip">Frame {frame.id}</span></div><div className="detail-layout">
    <div className="detail-visual panel"><img src={resolveMediaUrl(frame.preview_url||frame.source_url)} alt={frame.alt_text||film.title}/></div>
    <aside className="detail-report panel"><div className="eyebrow">Cinematography record</div><h1>{film.title}</h1><p className="detail-lede">{[film.year,film.director&&`Directed by ${film.director}`,film.cinematographer&&`Cinematography by ${film.cinematographer}`].filter(Boolean).join(" · ")||"Credits not supplied"}</p>
      <div className="provenance"><span>{film.metadata_origin==="user"?"User entered":"Source"}</span><a href={film.filmgrab_url.startsWith("http")?film.filmgrab_url:undefined} target="_blank" rel="noreferrer">{frame.source_type}</a>{shot&&<b>Shot {shot.shot_index+1} · {(shot.start_ms/1000).toFixed(1)}–{(shot.end_ms/1000).toFixed(1)}s</b>}</div>
      <button className="source-link" onClick={()=>setEditing(!editing)}>{editing?"Cancel":"Edit credits"}</button>{editing&&<form className="metadata-form" onSubmit={save}><input name="year" type="number" placeholder="Year" defaultValue={film.year||""}/><input name="director" placeholder="Director" defaultValue={film.director||""}/><input name="cinematographer" placeholder="Cinematographer" defaultValue={film.cinematographer||""}/><textarea name="production_credits" placeholder="Production credits" defaultValue={film.production_credits||""}/><button className="button-primary">Save metadata</button></form>}
      <h2 className="report-title">Shot DNA</h2>{error&&<div className="status-message">{error}</div>}{!d?<button className="button-accent" onClick={run} disabled={busy}>{busy?"Analyzing…":"Analyze this frame"}</button>:<>
        <div className="report-group"><h3>Frame</h3><div className="metric-grid"><Field label="Resolution" value={`${d.dimensions.width} × ${d.dimensions.height}`}/><Field label="Aspect ratio" value={`${d.dimensions.aspect_ratio}:1`}/></div></div>
        <div className="report-group"><h3>Colour & light</h3><div className="palette-row">{d.color.palette.map(c=><div key={c.hex} title={`${c.hex} · ${pct(c.weight)}`} style={{backgroundColor:c.hex}}/>)}</div><div className="metric-grid"><Field label="Average RGB" value={d.color.average_rgb.join(", ")}/><Field label="Saturation" value={pct(d.color.saturation)}/><Field label="Temperature bias" value={d.color.temperature_bias>0?"Warm":d.color.temperature_bias<0?"Cool":"Neutral"}/><Field label="Brightness" value={pct(d.luminance.brightness)}/><Field label="Contrast" value={pct(d.luminance.contrast)}/><Field label="Shadows / highlights" value={`${pct(d.luminance.shadows)} / ${pct(d.luminance.highlights)}`}/></div></div>
        <div className="report-group"><h3>Composition & quality</h3><div className="metric-grid"><Field label="Symmetry" value={pct(d.composition.symmetry)}/><Field label="Edge density" value={pct(d.composition.edge_density)}/><Field label="Visual centre" value={`${pct(d.composition.visual_center.x)} × ${pct(d.composition.visual_center.y)}`}/><Field label="Thirds distance" value={d.composition.nearest_third_distance}/><Field label="Sharpness" value={Math.round(d.quality.sharpness)}/><Field label="Exposure" value={d.quality.underexposed?"Underexposed":d.quality.overexposed?"Overexposed":"Balanced"}/></div></div>
        <div className="report-group estimates"><h3>Experimental estimates</h3><p>Classical heuristics, not camera or lens facts.</p><div className="metric-grid">{Object.entries(d.estimates||{}).map(([k,v])=><Field key={k} label={k.replaceAll("_"," ")} value={`${v.value} · ${pct(v.confidence)}`} kind="Estimated"/>)}</div></div>
        <p className="analysis-meta">Measured by {analysis.analyzer_name} v{analysis.analyzer_version} in {analysis.execution_ms.toFixed(1)} ms{media_asset?` · ${media_asset.original_name}`:""}</p></>}
    </aside></div></section>;
}
